question_data = [{"category": "Random Knowledge",
                  "data": [{"question": "A slug's blood is green.", "correct_answer": "True"},
                           {"question": "The loudest animal is the African Elephant.", "correct_answer": "False"},
                           {"question": "Approximately one quarter of human bones are in the feet.",
                            "correct_answer": "True"},
                           {"question": "The total surface area of a human lungs is the size of a football pitch.",
                            "correct_answer": "True"},
                           {"question": "In West Virginia, USA, if you accidentally hit an animal with your car, "
                                        "you are free to take it home to eat.", "correct_answer": "True"},
                           {"question": "In London, UK, if you happen to die in the House of Parliament, "
                                        "you are entitled to a state funeral.", "correct_answer": "False"},
                           {"question": "It is illegal to pee in the Ocean in Portugal.", "correct_answer": "True"},
                           {"question": "You can lead a cow down stairs but not up stairs.", "correct_answer": "False"},
                           {"question": "Google was originally called 'Backrub'.", "correct_answer": "True"},
                           {"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "correct_answer": "True"},
                           {"question": "No piece of square dry paper can be folded in half more than 7 times.",
                            "correct_answer": "False"},
                           {"question": "A few ounces of chocolate can to kill a small dog.", "correct_answer": "True"}]
                  },
                 {"category": "Science: Computers",
                  "data": [
                      {"question": "Linus Torvalds created Linux and Git.", "correct_answer": "True",
                       "incorrect_answers": ["False"]},
                      {"question": "Ada Lovelace is often considered the first computer programmer.",
                       "correct_answer": "True",
                       "incorrect_answers": ["False"]},
                      {
                          "question": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
                       "incorrect_answers": ["False"]}, {
                          "question": "The programming language 'Python' is based off a modified version of 'JavaScript'.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
                      {
                          "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
                       "incorrect_answers": ["True"]},
                      {"question": "Linux was first created as an alternative to Windows XP.",
                       "correct_answer": "False",
                       "incorrect_answers": ["True"]}, {
                          "question": "'HTML' stands for Hypertext Markup Language.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
                       "incorrect_answers": ["True"]}]},
                 {"category": "Politics",
                  "data": [
                      {
                          "question": "One of Barack Obama's United States presidential campaign slogan's was 'Yes We Can'.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                      {
                          "question": "Despite being separated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"question": "The S in Harry S. Truman stands for 'Samuel'.", "correct_answer": "False",
                       "incorrect_answers": ["True"]},
                      {"question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
                       "correct_answer": "False", "incorrect_answers": ["True"]},
                      {
                          "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
                          "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"question": "In 2016, the United Kingdom voted to stay in the EU.", "correct_answer": "False",
                       "incorrect_answers": ["True"]},
                      {
                          "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"question": "Denmark has a monarch.", "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"question": "There was a satirical candidate named 'Deez Nuts' running in the 2016 US presidential elections.", "correct_answer": "True", "incorrect_answers": ["False"]}]},
                 {"category": "Entertainment: Music",
                  "data": [
                      {"question": "Muse is a British (English) rock band", "correct_answer": "True",
                       "incorrect_answers": ["False"]},
                      {"question": "Michael Jackson wrote The Simpsons song 'Do the Bartman'.",
                       "correct_answer": "False", "incorrect_answers": ["True"]},
                      {"question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"question": "American rapper Dr. Dre actually has a Ph.D. doctorate.", "correct_answer": "False",
                       "incorrect_answers": ["True"]},
                      {"question": "The 2011 movie 'The Adventures of Tintin' was directed by Steven Spielberg.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {
                          "question": "The music video to The Buggle's 'Video Killed the Radio Star' was the first music video to broadcast on MTV.",
                          "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"question": "John Williams composed the music for 'Star Wars'.", "correct_answer": "True",
                       "incorrect_answers": ["False"]},
                      {"question": "The music group Daft Punk got their name from a negative review they recieved.",
                       "correct_answer": "True", "incorrect_answers": ["False"]},
                      {"question": "Korean girl group, TWICE, consists of 9 members", "correct_answer": "True",
                       "incorrect_answers": ["False"]},
                      {"question": "Stevie Wonder's real name is Stevland Hardaway Morris.", "correct_answer": "True",
                       "incorrect_answers": ["False"]}]},
                 {"category": "Animals",
                  "data": [{"question": "The Axolotl is an amphibian that can spend its whole life in a larval state.", "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"question": "Cats have whiskers under their legs.", "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"question": "The Killer Whale is considered a type of dolphin.", "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"question": "Rabbits are rodents.", "correct_answer": "False", "incorrect_answers": ["True"]},
                           {"question": "A bear does NOT defecate during hibernation. ", "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"question": "The freshwater amphibian, the Axolotl, can regrow it's limbs.", "correct_answer": "True", "incorrect_answers": ["False"]}, 
                           {"question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.", "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"question": "A slug's blood is green.", "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"question": "Rabbits can't vomit.", "correct_answer": "True", "incorrect_answers": ["False"]},
                           {"question": "Rabbits are carnivores.", "correct_answer": "False", "incorrect_answers": ["True"]}]}
                 ]
